export const GET_SERVICES = 'GET_SERVICES';
export const CREATE_SERVICE = 'CREATE_SERVICE';
export const GET_SERVICE = 'GET_SERVICE';
export const GET_SERVICE_NAME = 'GET_SERVICE_NAME';
export const FILTER = 'FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const ADD_ITEMS = 'ADD_ITEMS';
export const GET_TYPE_SERVICES = 'GET_TYPE_SERVICES';
export const DEL_ONE_SERVICE = 'DEL_ONE_SERVICE';
export const DEL_ALL = 'DEL_ALL';
export const PAYMENT_MP = 'PAYMENT_ MP'
export const INITIATE_PAYMENT = 'INITIATE_PAYMENT'
